### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by lhrb** [lhrb/swec8#1]
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at com.github.lhrb.nemo.actors.ActorPrefab.<init>(ActorPrefab.java:46)
        at com.github.lhrb.nemo.actors.enemies.Enemy.collision(Enemy.java:40)
        at com.github.lhrb.nemo.actors.CollisionManager.checkCollision(CollisionManager.java:50)
        at com.github.lhrb.nemo.screen.FirstLevelScreen.update(FirstLevelScreen.java:40)
        at com.github.lhrb.nemo.screen.AbstractScreen.render(AbstractScreen.java:62)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
```

**Comment by lhrb** [comment]
Sollte jetzt fixed sein

**Comment by cwaninger** [comment]
Close, da bereits gefixt und verifiziert.
